name: googledriveclone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.5
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  google_sign_in: ^6.2.1
  syncfusion_flutter_pdfviewer: ^26.1.39
  video_player: ^2.8.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/